---
- hosts: server
  become: yes
  tasks:

  - name: Add repo PGDG
    yum:
      name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
      state: installed

  - name: install PostgreSQL and barman
    yum:
      name:
        - postgresql11-server
        - postgresql11-contrib
        - barman

  - name: init cluster
    shell:
      /usr/pgsql-11/bin/postgresql-11-setup initdb

  # - name: copy postgresql.auto.conf file
    # copy: src=postgresql.auto.conf dest=/var/lib/pgsql/11/data/postgresql.auto.conf owner=postgres group=postgres mode=0600

  - name: postgresql restart
    systemd:
      name: postgresql-11
      state: restarted
      enabled: yes

  - name: set the password for the postgres user in the postgresql cluster
    postgresql_query:
      db: template1
      login_user: postgres
      query: ALTER USER postgres PASSWORD 'otus'
    become_user: postgres

  # - name: copy pgpass to pgsqlMaster
  #   copy: src=pgsqlMaster_pgpass dest=/var/lib/pgsql/.pgpass owner=postgres group=postgres mode=0600
  #   when: ansible_facts['hostname'] == "pgsqlMaster"

  # - name: copy pgpass to pgsqlSlave
  #   copy: src=pgsqlSlave_pgpass dest=/var/lib/pgsql/.pgpass owner=postgres group=postgres mode=0600
  #   when: ansible_facts['hostname'] == "pgsqlSlave"

  - name: create a new database "otusdb"
    postgresql_db:
      name: otusdb
      encoding: UTF-8
      template: template1
    become_user: postgres

  - name: Create replication user
    postgresql_user:
      name: replication
      password: replication
      role_attr_flags: REPLICATION
    become_user: postgres

  # - name: Set wal2
  #   postgresql_set:
  #     name: max_wal_senders
  #     value: 3
  #   become_user: postgres
  # - name: Set wal3
  #   postgresql_set:
  #     name: wal_keep_segments
  #     value: 128
  #   become_user: postgres  
  # - name: Set wal4
  #   postgresql_set:
  #     name: wal_level
  #     value: replica
  #   become_user: postgres

  - name: Grant user replication from network 172.20.10.0/24 access for replication
    postgresql_pg_hba:
      dest: /var/lib/pgsql/11/data/pg_hba.conf
      contype: host
      users: replication
      source: 172.20.10.0/24
      databases: replication
      method: md5
    become_user: postgres

  - name: postgresql restart
    systemd:
      name: postgresql-11
      state: restarted
      enabled: yes