---
- hosts: server
  become: yes
  tasks:

  - name: Add repo PGDG
    yum:
      name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
      state: installed

  - name: install PostgreSQL and barman
    yum:
      name:
        - postgresql11-server
        # - postgresql11-contrib
        - barman

  - name: init cluster
    shell:
      /usr/pgsql-11/bin/postgresql-11-setup initdb
  
  - name: copy config files
    copy:
      src=postgresql_master.conf
      dest=/var/lib/pgsql/11/data/postgresql.conf
      owner=postgres
      group=postgres
      mode=0600

  - name: copy pg_hba files
    copy:
      src=pg_hba.conf
      dest=/var/lib/pgsql/11/data/pg_hba.conf
      owner=postgres
      group=postgres
      mode=0600

  - name: postgresql restart
    systemd:
      name: postgresql-11
      state: restarted
      enabled: yes

  - name: set the password for the postgres user in the postgresql cluster
    postgresql_query:
      db: template1
      login_user: postgres
      query: ALTER USER postgres PASSWORD 'otus'
    become_user: postgres

  - name: create a new database "otusdb"
    postgresql_db:
      name: otusdb
      encoding: UTF-8
      template: template1
    become_user: postgres

  - name: Create replication user
    postgresql_user:
      name: replication
      password: replication
      role_attr_flags: REPLICATION
    become_user: postgres

  - name: Create barman user
    postgresql_user:
      name: barman
      password: barman
      role_attr_flags: SUPERUSER,NOCREATEDB,NOCREATEROLE
    become_user: postgres

  - name: Create streaming_barman user
    postgresql_user:
      name: streaming_barman
      password: barman
      role_attr_flags: LOGIN,REPLICATION
    become_user: postgres

  - name: Edit /etc/hosts
    shell: echo "172.20.10.51    web" >> /etc/hosts

  # - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
  #   openssh_keypair:
  #      path: /var/lib/pgsql/.ssh

  - name: Copy private key
    copy:
      src=/vagrant/keys/server/id_rsa
      dest=dest=/var/lib/pgsql/11/data/.ssh/
      owner=barman
      group=barman

  - name: Set authorized key WEB taken from file
    authorized_key:
      user: postgres
      state: present
      key: "{{ lookup('file', '/vagrant/keys/web/id_rsa.pub') }}"

  - name: postgresql restart
    systemd:
      name: postgresql-11
      state: restarted
      enabled: yes