---
- hosts: web
  become: yes
  tasks:

  - name: Add repo PGDG
    yum:
      name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
      state: installed

  - name: install PostgreSQL and barman
    yum:
      name:
        - postgresql11-server
        # - postgresql11-contrib
        - barman

  - name: Copy files from db server
    shell: echo "replication"|pg_basebackup -h 172.20.10.50 -U replication -D /var/lib/pgsql/11/data/ --wal-method=stream
    become_user: postgres  

  - name: copy config files Postgresql
    copy:
      src=postgresql_web.conf
      dest=/var/lib/pgsql/11/data/postgresql.conf
      src=recovery.conf
      dest=/var/lib/pgsql/11/data/recovery.conf
      owner=postgres
      group=postgres
      mode=0600

  - name: copy config files Barman
    copy:
      src=server_web.conf
      dest=/etc/barman.d/server.conf

  - name: Copy pgpass
    copy:
      src=pgpass
      dest=/var/lib/barman/.pgpass
      owner=barman
      group=barman
      mode=0600

  - name: Edit /etc/hosts
    shell: echo "172.20.10.50    server" >> /etc/hosts  


  - name: Copy private key
    copy:
      src=/vagrant/keys/web/id_rsa
      dest=/var/lib/barman/.ssh/
      owner=barman
      group=barman

  - name: Set authorized key SERVER taken from file
    authorized_key:
      user: barman
      state: present
      key: "{{ lookup('file', '/vagrant/keys/server/id_rsa.pub') }}"

  - name: postgresql restart
    systemd:
      name: postgresql-11
      state: restarted
      enabled: yes